(env) samimchala@Samis-MacBook-Pro-2 myproject % nile compile
ü§ñ Compiling all Cairo contracts in the contracts directory
üî® Compiling contracts/one_to_one.cairo
‚úÖ Done


(env) samimchala@Samis-MacBook-Pro-2 myproject % nile deploy one_to_one --alias 6_contract --network goerli                  
üöÄ Deploying one_to_one
‚è≥ Ô∏èDeployment of one_to_one successfully sent at 0x034e5898bed5b94c9d5319d1b1716a63e725921598f2b7b2ae1ed2c84f6b5c33
üßæ Transaction hash: 0x29535d05a8aa90f8cb420a385da590fa514c0b67f0cebf2c47f8d41ce7678e5
üì¶ Registering deployment as 6_contract in goerli.deployments.txt



(env) samimchala@Samis-MacBook-Pro-2 myproject % nile call 6_contract set_receipients 123456789 33 --network goerli
Got BadRequest while trying to access https://alpha4.starknet.io/feeder_gateway/call_contract?blockNumber=null. Status code: 500; text: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Contract with address 0x34e5898bed5b94c9d5319d1b1716a63e725921598f2b7b2ae1ed2c84f6b5c33 is not deployed."}.
Traceback (most recent call last):
  File "/Users/samimchala/Documents/projects/myproject/env/lib/python3.7/site-packages/services/external_api/base_client.py", line 120, in _send_request
    raise BadRequest(status_code=response.status, text=text)
services.external_api.base_client.BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Contract with address 0x34e5898bed5b94c9d5319d1b1716a63e725921598f2b7b2ae1ed2c84f6b5c33 is not deployed."}
Error: BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Contract with address 0x34e5898bed5b94c9d5319d1b1716a63e725921598f2b7b2ae1ed2c84f6b5c33 is not deployed."}
Traceback (most recent call last):
  File "/Users/samimchala/Documents/projects/myproject/env/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Users/samimchala/Documents/projects/myproject/env/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/samimchala/Documents/projects/myproject/env/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/samimchala/Documents/projects/myproject/env/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/samimchala/Documents/projects/myproject/env/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/samimchala/Documents/projects/myproject/env/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/samimchala/Documents/projects/myproject/env/lib/python3.7/site-packages/nile/cli.py", line 132, in call
    out = call_or_invoke_command(contract_name, "call", method, params, network)
  File "/Users/samimchala/Documents/projects/myproject/env/lib/python3.7/site-packages/nile/core/call_or_invoke.py", line 40, in call_or_invoke
    return subprocess.check_output(command).strip().decode("utf-8")
  File "/Users/samimchala/.pyenv/versions/3.7.12/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Users/samimchala/.pyenv/versions/3.7.12/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['starknet', 'call', '--address', '0x034e5898bed5b94c9d5319d1b1716a63e725921598f2b7b2ae1ed2c84f6b5c33', '--abi', 'artifacts/abis/one_to_one.json', '--function', 'set_receipients', '--inputs', '123456789', '33']' returned non-zero exit status 1.


(env) samimchala@Samis-MacBook-Pro-2 myproject % nile debug 0x034e5898bed5b94c9d5319d1b1716a63e725921598f2b7b2ae1ed2c84f6b5c33
‚è≥ Querying the network to check transaction status and identify contracts...
üïí Transaction status: NOT_RECEIVED. Trying again in a moment...
üïí Transaction status: NOT_RECEIVED. Trying again in a moment...
üïí Transaction status: NOT_RECEIVED. Trying again in a moment...